import {
  AlertTriangle,
  ArrowRight,
  Award,
  BarChart3,
  Bell,
  Bot,
  Calendar,
  CalendarDays,
  CheckCircle,
  ChevronRight,
  FileText,
  Gift,
  Heart,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  Search,
  TrendingUp,
  Trophy,
  Users,
  X,
  Activity,
  type LucideIcon,
} from "lucide-react"

export type { LucideIcon as Icon }

export const Icons = {
  logo: Heart,
  close: X,
  menu: Menu,
  search: Search,
  trendingUp: TrendingUp,
  barChart: BarChart3,
  bell: Bell,
  calendar: Calendar,
  gift: Gift,
  bot: Bot,
  chevronRight: ChevronRight,
  alertTriangle: AlertTriangle,
  users: Users,
  map: Map,
  award: Award,
  fileText: FileText,
  checkCircle: CheckCircle,
  messageCircle: MessageCircle,
  calendarDays: CalendarDays,
  mapPin: MapPin,
  heartHand: Heart,
  trophy: Trophy,
  activity: Activity,
}
