// STUB — auto-generated by preflight. The builder replaces this file
// with a real createClient(...) call once Supabase is connected.
// Do NOT import from `@supabase/supabase-js` anywhere else in the frontend.

export const supabase: any = null
